name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: python-backend-api-419906
  RUN_REGION: us-central1 
  SA_KEY_JSON: ${{ secrets.SA_CREDS }}
  # API_KEY: ${{ secrets.API_KEY }}
  # SECRET_KEY: ${{ secrets.SECRET_KEY }}
  # OPENAI_API_KEY: ${{ secrets.OAI_API_KEY}}

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest

    env:
      # Replace $PROJECT_ID with your project ID
      IMAGE_NAME: gcr.io/python-backend-api-419906/python-app

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # NOTE: Alternative option - authentication via credentials json
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SA_CREDS }}'

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME

      - name: Push Docker image
        run: docker push $IMAGE_NAME
      
      - id: deploy
        name: Deploy Docker image
        uses: "google-github-actions/deploy-cloudrun@v0"
        with:
          image: ${{ env.IMAGE_NAME }}
          region: ${{ env.RUN_REGION }}
          service: python-app
          flags: --port=8080 --allow-unauthenticated
          set-env-vars:
            API_KEY: test123